### ISSUE TITLE
More keyboard shortcuts

### ISSUE THREAD

**Issue by DFyson** [activityworkshop/GpsPrune#10]
I would love more keyboard shortcuts to improve the speed. For example duplicating nodes, opening the edit node window, etc.

**Comment by activityworkshop** [comment]
The point edit window has a toolbar icon as well as a menu entry, but I understand a key shortcut would be faster - any preferences for which key (in English) would make sense?
Duplicating nodes isn't something I need to do very often, is your usage related to photographs?

**Comment by DFyson** [comment]
Something like Ctrl-E comes to mind for edit window. As for duplicating nodes, the only reason I was thinking of using it was as a way of copying info for a bunch of specific nodes since duplicating appends to end of GPX file then just open the file and copy the last lines to a spreadsheet.  #9 is trying to achieve the same but copying to clipboard then to a file.

How about a shortcut manager? So then you wouldn't have to worry about setting shortcuts for everything, leave that up the to user as they see fit to increase their productivity and not have to request it and wait for a development cycle. JOSM for example has this and I really like it (partially because my delete key is broken so I remapped it to backspace). I wish all programs had it. I just don't know how complicated that would be to program... maybe adapt what JOSM has since it's also java?

**Comment by theHedster** [comment]
GPSprune is a graphics program, in a sense. Graphics programs in general allow the user to steer and operate the mouse with the right hand, and use the left hand for key shortcuts, making these programs very efficient and productive. 

I see that a few shortcuts have been implemented but many more would increase the efficiency. I note that you have to take a screenshot to make a reference card for the existing screen shots. It would help users to learn the key shortcuts by showing them after the menu commands.

**Comment by activityworkshop** [comment]
Just a quick update - this is how the key shortcuts are shown after the menu commands, as you requested.  And it includes Ctrl-E for Edit point.

![menus](https://github.com/activityworkshop/GpsPrune/assets/11003522/64bd110d-e31b-45bc-9217-f5fdc68ddc74)

**Comment by activityworkshop** [comment]
I think this is done, unless there are any more specific requests.
