### ISSUE TITLE
[Feature request] When interpolating points, interpolate also time

### ISSUE THREAD

**Issue by jdbonjour** [activityworkshop/GpsPrune#102]
When using Range>Interpolate points, GpsPrune correctly interpolate elevation for new points. But if the track points contain also time fields, GPSprune doesn't add a interpolated time to news points. It would be a very interested feature.

**Comment by activityworkshop** [comment]
Good idea.  Usually I use this interpolation feature during the planning stage, when the points don't have timestamps.  But I guess it might also be useful in the editing stage with recorded points too.

**Comment by jdbonjour** [comment]
Nice, thanks very much in advance !

**Comment by activityworkshop** [comment]
Extended with version 24.3.
Thanks for the suggestion.

**Comment by jdbonjour** [comment]
Ouaouh, great, thanks so much !

Le mar. 20 août 2024 à 19:13, activityworkshop ***@***.***> a
écrit :
