### ISSUE TITLE
Point dragging using L-ALT blocked on xfce desktop

### ISSUE THREAD

**Issue by mbretter** [activityworkshop/GpsPrune#18]
The point dragging feature is blocked on Xfce desktops, L-ALT + Click is assigned to dragging windows on Xfce desktops, making impossible to drag points on gpsprune.

Some kind of configurable keybindings would be neat, or adding the point moving option to the right click menu would help a lot.

cheers

**Comment by activityworkshop** [comment]
Dragging with Left-Alt also drags the whole window for me, even though I don't use xfce.
Point dragging doesn't use left-alt, it uses Alt-Gr.  Does that work for you?
Alternatively you can (temporarily) activate "edit mode" using the little hand icon at the top of the map pane, then dragging points doesn't require the Alt-Gr key (but it's then easier to do accidentally).

Good idea about making the modifier key configurable, I'll add it to the list.  I'm not sure what could be added to the right-click menu though, unless you mean activating / deactivating the edit mode?

**Comment by mbretter** [comment]
ah great, thx for your hints.

> 
> Good idea about making the modifier key configurable, I'll add it to the list. I'm not sure what could be added to the right-click menu though, unless you mean activating / deactivating the edit mode?

exactly, that would be a good improvement
