### ISSUE TITLE
Range Details Duration Error

### ISSUE THREAD

**Issue by sawoods** [activityworkshop/GpsPrune#2]
The duration for a selected range shown in 'Range Details' appears to be incorrect
The duration for a range shown in  View > 'Full Range Details' is correct

![screen shot 2015-08-22 at 12 08 03](https://cloud.githubusercontent.com/assets/13916656/9423678/a83bf4c2-48c6-11e5-8cec-6acb6dd7b545.png)

![screen shot 2015-08-22 at 12 08 26](https://cloud.githubusercontent.com/assets/13916656/9423680/b6bd4c9e-48c6-11e5-8a1b-40806bff8261.png)

![screen shot 2015-08-22 at 12 25 18](https://cloud.githubusercontent.com/assets/13916656/9423725/fb5fa9a8-48c8-11e5-8c06-d98e4472bf1e.png)

**Comment by activityworkshop** [comment]
Thanks very much for the feedback.  As discussed on sourceforge, this was a bug with the comparison of subsecond timestamps.  Closed with the release of version 18.1
