### ISSUE TITLE
GPSPrune 20 Won't open - OS X 10.14.6

### ISSUE THREAD

**Issue by xenakes** [activityworkshop/GpsPrune#25]
GPSPrune 20 will not open on Mac with OS X 10.14.6. Version 19 works. All I get is a message saying to check the Console and below is what I find.

syspolicyd
added rule for gpsprune_20.jar
com.apple.message.domain: com.apple.security.assessment.update
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: gpsprune_20.jar
com.apple.message.signature5: UNKNOWN
SenderMachUUID: 5D0A1EC6-519B-3224-84D1-59998AF98FD7

CoreServicesUIAgent
added rule for gpsprune_20.jar
com.apple.message.domain: com.apple.security.assessment.update
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: gpsprune_20.jar
com.apple.message.signature5: UNKNOWN
SenderMachUUID: 4457A7F2-E652-305A-8C01-9D541775114E

**Comment by activityworkshop** [comment]
Could you please try again with https://gpsprune.activityworkshop.net/gpsprune_20_java6.jar ?
Or if that doesn't work, please post the result of "java -version".  Thanks.

**Comment by xenakes** [comment]
That version worked. Thank you.

Java -version shows
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

but if I go to system preferences Java, Java Control Panel it shows my current version is Java 8 Update 231

**Comment by activityworkshop** [comment]
Great.  I've published this additional jar on the download page, so I'll close this issue now.
