### ISSUE TITLE
When tile cache "root" doesn't exists there is no error message but no bckground map either

### ISSUE THREAD

**Issue by sebastic** [activityworkshop/GpsPrune#29]
As reported by Peter Gervai in [Debian Bug #973910](https://bugs.debian.org/973910):
> The cache was created in a directory which got cleaned [full of temporary stuff].
> gpsprune cache directory was removed, too.
> gpsprune don't warn the user at the start but due to missing dir it cannot retrieve
> background map tiles and cannot display them, which is very confusing.
> I had to strace it to see that file creates fail with "no such file or directory".

**Comment by kaoneko** [comment]
So that's what's going on. Thank you! I guess cleaning the system cache out with BleachBit causes this issue. Drove me crazy! 

Quick fix for anyone else reading this: (temporarily) disable Settings > Save maps to disk - and there's your map background!

**Comment by activityworkshop** [comment]
temporarily disabling saving the maps to disk isn't the best solution, as then nothing will be saved.  It's better to _enable_ saving maps to disk and to choose where to save them to - then the folder will be properly created if necessary.

**Comment by kaoneko** [comment]
Yeah I worded it a bit weird, but I meant to say to toggle the setting 😅
Thanks for the great application by the way!

**Comment by activityworkshop** [comment]
behaviour now improved with 20.1, so closing
