### ISSUE TITLE
SRTM tile download failed 20.2

### ISSUE THREAD

**Issue by romanlinhard** [activityworkshop/GpsPrune#33]
Hello,

here are my note to an new possible download source:
srtm.kurviger.de

Please check, if that is possible.

All the best
Roman

**Comment by jose1711** [comment]
Fixed in 20.3.

**Comment by activityworkshop** [comment]
Thanks to @romanlinhard  for suggesting the alternative source, and special thanks to kurviger.de (a route planning service and forum for motorcycles) for allowing GpsPrune to use their mirror.
