### ISSUE TITLE
Request a new feature. Add middle speed.

### ISSUE THREAD

**Issue by xb3b6** [activityworkshop/GpsPrune#35]
If the GPX track is missing 'speed' or cleaned field 'speed' you need to add a middle speed to the entire GPX track. At the moment I met this feature only at http://www.gpstrackeditor.com/download
![gpstrackeditor](https://user-images.githubusercontent.com/80679015/114507588-00c7d880-9c3c-11eb-85bd-0151fbe5d4b4.png)

**Comment by activityworkshop** [comment]
I think what you mean by "Add middle speed" is that you want to create "fake" timestamps for all the points in the track.  There are different ways to do this but you're right, GpsPrune doesn't have a way to automatically fake timestamps like this itself.

One way would be to use the distances between each point and use a constant speed to calculate the time increments - I think this is what your screenshot is proposing. It's not clear to me how waypoints would be given timestamps in this case.

Another way might be just to create a timestamp each second and apply it to the next point in the track - this is simpler and covers the waypoint case too. Of course it's then very obvious that the timestamps are faked, but I think that's not a problem, it's going to be obvious anyway even with your perfectly constant speed and I guess that doesn't matter.

Also I don't know a good way to select the first timestamp (date/time) to use, we don't currently have any controls to easily specify this.  So either they would be bare text entry fields (with high probability of parse errors) or we'd need to find some more complex alternative (or just default to "now"). Currently I don't know how important a use case this is, how many people might use such a feature, and how much effort it's worth investing in a solution.

**Comment by activityworkshop** [comment]
Side note: if you clean or delete the 'speed' field of a track, this doesn't (or shouldn't) delete the timestamps of each point. So the speeds can still be calculated using the timestamps and distances, although they may not match exactly.

**Comment by xb3b6** [comment]
I'm not sure if the waypoints need anything other than coordinates (anyway, I only use waypoints as markers).  As for "the need for a functional and who uses the average speed function", you can conduct a survey through google forms and insert it into the github/site.  For me, this is the necessary functionality, I would not ask for it if gpstrackeditor would work well in Linux through wine (but alas, it barely works like that, and there are no alternatives).

**Comment by activityworkshop** [comment]
OK. Why do _you_ want these timestamps on the track points?  What will _you_ use them for?
I know that some services require timestamps on uploaded gpx tracks, but as far as I know they don't need to mean anything.

**Comment by xb3b6** [comment]
Sorry, I think I lost the essence of the conversation.

1. There is a GPS track. His parameters (height, time, pulse). You need a function that can edit the time (to adjust the total average speed).
2. There are track points of the track (these are special points on the track, they are not interested in me and are used mainly as markers)

**Comment by activityworkshop** [comment]
You want to adjust the total average speed, why?  Do you want to see what the timestamps _would be_ if your speed were perfectly constant?  You want to see where you could get to if you could increase your running time to <x> km/h ?

**Comment by xb3b6** [comment]
One example.
I travel a week (it happens more) and write every day along the track, then I combine all parts of the track (7 days/tracks) to one file.gpx and set up a real overall average speed and get one full-fledged track length a week travel. Later, I can unload track, for example, https://www.relive.cc/, which takes data (average speed) and creates video animation from the track.

Example:
![ll1](https://user-images.githubusercontent.com/80679015/117004350-a24bc280-acee-11eb-9931-6d1b27a878ca.jpg)

**Comment by activityworkshop** [comment]
It's not _quite_ what you were asking for, but version 21 now includes the option to **apply** the timestamps produced by the "estimate time" function to the selected range.  So it can kind of do what you want, but this way it provides something much more useful than just being able to fake timestamps, you can also use it for estimation (especially if you get GpsPrune to learn the parameters first).

The timestamps start at midnight rather than ask you for the start time, but you can then use the existing "add time offset" function to change it to something else.
