### ISSUE TITLE
How to shift Start and End point of a track which is a loop?

### ISSUE THREAD

**Issue by anishmittal2020** [activityworkshop/GpsPrune#40]
I downloaded [GPX File](https://bikemike.net/wp-content/uploads/2020/10/BikeMike-_-Bad-Wiessee-Valepp-Tal-Spitzing-Schliersee-Bad-Wiessee.7z), from [A dream tour from Tegernsee to Tegernsee - BikeMike](https://bikemike.net/eine-traumrunde-vom-tegernsee-zum-tegernsee/). 

### Observation 

This is a circular track starting and ending at the same point: `Bad-Wiessee`. Now If I want to shift the start and end points to some other place, (so I don't want to crop the route), how can I do it?

For example I want to start at a point near `Hausham` and I went to end it there, so that the bottom window that shows the altitude shift accordingly, and the index of each points shifts accordingly. 

How can I do it

**Comment by activityworkshop** [comment]
Click on the point near Hausham where you want the loop to start (maybe by point 1084).
Select from this point onwards (Range -> Set Start)
Go to the start of the track (Ctrl Home)
Cut the selected section (from Hausham onwards) to go before the currently selected point (Range -> Cut & Move selection, or the scissors button)
And then I assume you want to make it a single segment:
Select All (Ctrl A)
Merge all segments into one (Range -> Merge track segments)

**Comment by activityworkshop** [comment]
You're welcome.
