### ISSUE TITLE
Is KMZ fully supported?

### ISSUE THREAD

**Issue by anishmittal2020** [activityworkshop/GpsPrune#41]
I opened a KMZ file (created in Google Mymaps), that has a KML with several layers and  several icons in images folder of KMZ archive.

On importing all layer POI and tracks were merged into a single layer. All icons of POI were replaced by one of the predefined icon in the settings. Is it possible to support these features?

**Comment by activityworkshop** [comment]
No, GpsPrune doesn't support all the features of kmz, it's not a kmz editor.
It doesn't have the concept of layers, so all data from all layers is combined.  If you want to keep the layers separate, use separate Tracks (ie, separate files).

Custom POI icons are also not supported, the display of waypoint icons is controlled inside GpsPrune's settings (Set display options) but all waypoints are shown the same.  You might like to read issue 3 https://github.com/activityworkshop/GpsPrune/issues/3 but any solution must be able to handle multiple file types (not just kmz) and multiple GPS devices.

**Comment by activityworkshop** [comment]
no response so closing.
