### ISSUE TITLE
Serious usability issue: Join track ranges?

### ISSUE THREAD

**Issue by Gnlfz007** [activityworkshop/GpsPrune#42]
I'm drawing a track and I have to stop with ESC half way done because of an error.
Then I want to continue the track. I cannot manage this after 1 hour of consulting the howto and other resources found in the internet.  The function "sew together" throws always an error message and there is not other feature which could do this. Is this possible al all?!

This issue renders Gpsprune completely useless because connecting track ranges is a standard use-case.

**Comment by activityworkshop** [comment]
no response to the question about which "common GUI applications" handle segment drawing differently, so closing.
