### ISSUE TITLE
GpsPrune 21 is unredistributable, GPL-2 is incompatible with GPL-3+

### ISSUE THREAD

**Issue by sebastic** [activityworkshop/GpsPrune#44]
GpsPrune 21 includes the BitmapEncoder source which is licensed under the terms of the GPL-3+:
```
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
```

GpsPrune is licensed under the terms of the GPL-2 (no later version):
```
GpsPrune is copyright 2006-2021 activityworkshop.net and distributed under the terms of the Gnu GPL version 2.
```

GPL-2 is unfortunately incompatible with GPL-3+, the GPL-2 code needs to include the "or (at your opinion) any later version" clause to become GPL-2+ which can be upgraded to GPL-3+ when combined which such sources, see:

 https://www.gnu.org/licenses/license-list.en.html#GPLv2

**Comment by activityworkshop** [comment]
Hi Bas, sorry about that, that was my mistake.
With the updated tarball, the BitmapEncoder class is now removed and so there shouldn't be any licensing problem.

**Comment by sebastic** [comment]
Thanks for the fix, although modifying published tarballs is not good. Publishing a new patch release would have been better.

**Comment by activityworkshop** [comment]
Aha, you mean something like `gpsprune_21_source_patch2`.  Yes, good point.  I mean, the normal case is that a code change would be required so you'd get 21.1 without a patch number, but in this case I don't have a naming scheme defined where I can release a patch of the tarball for the same version number.  I'll think about it.

**Comment by sebastic** [comment]
No, I meant something like `gpsprune_21.1`.

Once a release is published, modifications should use a higher version number.
