### ISSUE TITLE
SVG bug

### ISSUE THREAD

**Issue by PezzeyRaus** [activityworkshop/GpsPrune#45]
There is a bug with SVG images, they are not displayed in Chrome/Chromium when referenced in an img-tag. Also my old illustrator (CS6) does not like to read them. I assume Chrome requires a line like `<dc:format>image/svg+xml</dc:format>` in the SVG file.

A workaround is to load the SVGs in GIMP or similar and export them again with a small action (clean up for example).

**Comment by activityworkshop** [comment]
Um... GpsPrune doesn't write SVGs any more, and hasn't for quite some time.
What old version of GpsPrune are you using?
(Note, that means any changes required to please Chromium won't happen either).

**Comment by PezzeyRaus** [comment]
Hi, my version is not that old, but just one year old (20.4). I use GPSPrune exclusively to create these SVG charts for my website (they are the most beautiful ones I could find) and there are quite a few of these elevation profiles in it. Normally I use FF as my browser and everything ran and runs fine. But when I recently installed additional Chromium on my Linux netbook, I noticed this bug. 

A little research revealed that this behaviour is known and wanted by Chromium, for whatever reason. Instead of the sometimes adventurous actions suggested on the net, it seemed most advisable to me to update the SVGs with GIMP, and that worked. As far as I know, GIMP creates the best and most "regular" SVGs of all vector graphics programms, better than Adobe Illustrator. Of course, all this can also be a problem with Gnuplot (and yes, I have the latest version).

If the latest GPSPrune versions no longer support the SVG diagrams, the problem will be solved anyway, I ran all the diagrams through GIMP via script and now everything is fine again for me.

Gut, dass ich alter Datenmessi alte Software nicht lösche :-)

**Comment by activityworkshop** [comment]
I'm glad that everything is now fine, please feel free to close the ticket if you think you have a way around the problem.
Just for your information, GpsPrune doesn't create those SVGs from the charts itself, that's the job of the separate program "Gnuplot", so if the SVG needs fixing then only the Gnuplot developers can do that.  If the rendering of the SVGs needs fixing then that's for the Chromium developers.

By the way, I'd be surprised if "GIMP creates the best and most "regular" SVGs" - according to my understanding Gimp is only able to _import_ the SVGs, but anything saved from Gimp must be in some kind of raster format like png.  So you'd lose the resolution-independence if you go via that route (if I'm not wrong about Gimp's abilities).  If you want to "update the SVGs" (ie, create another SVG from the Gnuplot-created SVG), then I'd recommend a vector tool like Inkscape, and save it as type "Plain SVG".  Maybe Chromium likes those better?  (I'm not familiar with the "known and wanted" behaviour you refer to).  On the other hand, maybe png is better for the web anyway, and maybe an optimiser could help too.

**Comment by PezzeyRaus** [comment]
Yeah, I meant Inkscape of course, a bug of mine. Gimp just creates a pixel image embedded in an SVG frame. So, then I will close the ticket. Thank you for the attention.
