### ISSUE TITLE
wishlist: more display-options for 3D-View

### ISSUE THREAD

**Issue by jannis701** [activityworkshop/GpsPrune#49]
I really like the 3D-View-Feature of GpsPrune. It's the only way for me, to visualize my glider-flights in 3D without uploading them somewhere.  I'm using the debian-packaged version 20.2 of gpsprune with openjdk-11. unfortunately thats the only way/versions, in which the 3D-view is working on my system, so I was not able to test a newer version. (in Version 21.2 of the website, using openjdk-11 it complains, that no Java3D is found. using openjdk-8 it find java3D but crashes "Exception in thread "J3D-Renderer-1" java.lang.NoSuchMethodError: sun.awt.X11GraphicsConfig.getDevice()"... but thats another topic).

It would be really nice, if it would be possible to make the 3D-Tracks look a little bit nicer. espacially the possibility of defining the radius of the balls and the cylinders under them (to make both of them smaller) would help to get a more clear view.

**Comment by activityworkshop** [comment]
1 - if you're using Debian Stable, you can get GpsPrune 21.2 from stable-backports, and the 3d will work out of the box.

2 - I'm assuming you're talking about the Java3d rendering like in the following examples:
https://activityworkshop.net/software/gpsprune/screengrabs/gpsprune_20_j3d.jpg
https://activityworkshop.net/software/gpsprune/screengrabs/gpsprune_21_3daerial.jpg

and not the subjectively "nicer" rendering from povray like this one:
https://activityworkshop.net/software/gpsprune/screengrabs/prune_06_paragliding_pov.png

For your glider flights the relationship to the ground is obviously different from my ground-based tracks, but I think if I made my points and cylinders much smaller then it would be more difficult to see them clearly.  Are you proposing an option to make them for example 50% of the current size?  10% ?  Perhaps if you have long flights with huge distances involved then you need the points smaller, or if you have multiple circling motions then the different "laps" get merged together with the current settings?  I think I get what you're asking for but I just like to understand properly.

So a single "track scaling factor" with a percentage would be enough for you?  But closing and re-opening the 3d view with a different percentage would still be awkward I guess (it's the same for the vertical exaggeration, unfortunately).

**Comment by jannis701** [comment]
1 - thanks for the hint with stable-backports, I'll give it a try tomorrow.

2 - glider-flights are elevated over the ground and have spirals which are barely visible in the current view: 
![2022-04-16_22-02](https://user-images.githubusercontent.com/23027400/163689867-a737b247-d13a-4796-8ea2-db7febb5117c.jpg) (flight randomly taken from https://www.dhv-xc.de/ )
I think the "balls" have to be smaller to see the spirals and the grey cylinders should be thin lines or absent, to have a nice view. I'm not sure, what are the best values (50%, 10%, ...) that's why I would suggest an input-field to change the radius-size of the objects.

closing and reopening with other settings would be ok for me. i think, I'll soon figure out the good values.

**Comment by activityworkshop** [comment]
Thanks for the link to the tracks, they're fantastic!
I don't think that removing the cylinders makes things nicer, in my opinion it just makes it _really_ difficult to see whether the track is close to the ground further away from the viewer or close to the viewer and really high above the ground.  It's not so bad when you're interactively dragging the model around, you can see the 3d effect, but when it stops moving you lose the perspective.

![3d_no_cylinders](https://user-images.githubusercontent.com/11003522/163710307-8323126b-0600-458e-8087-6b0fcaa142b2.jpg)

Controlling the size and/or opacity would be preferable, I think.

**Comment by jannis701** [comment]
yes, I agree. controlling the opacity of the cylinders is also a very good idea.

**Comment by activityworkshop** [comment]
Here's what it looks like with the radii reduced to 20% of their normal values - and you're right, with a complex airborne track like this one it really helps to see the fine detail.  So I guess that choosing a range from 5% to 200% should be sufficient for most people.

![3d_at_twenty_percent](https://user-images.githubusercontent.com/11003522/164067418-237a20d8-f4a9-4755-8091-669e24c73dd2.jpg)

And I assume that the same scaling factor (not quite sure what to call it yet) would also be carried forward to the Pov export too.  Probably just using a text entry field like the altitude exaggeration?

I haven't touched the opacity yet (I'm still not sure whether it's needed).  Depending on the spacing between the track points and the overall scale of the track, you will start to see gaps between the cylinders when the radius is decreased anyway.

**Comment by activityworkshop** [comment]
![3d_config](https://user-images.githubusercontent.com/11003522/164976966-cd68314c-54d7-4801-85f0-75f1ea50c3d8.png)

**Comment by jannis701** [comment]
looks good to me! I'm looking forward to the release, where this is built in :)

**Comment by activityworkshop** [comment]
done :)
