### ISSUE TITLE
Caching of map tiles: disk cache time limit and file deletion

### ISSUE THREAD

**Issue by jbergenthal2** [activityworkshop/GpsPrune#5]
I have noticed the disk cache files are deleted after 20 days of downloading.
However, this happens even if there is no internet connection.
So after twenty days my offline computer loses all its maps and I have to refresh all the maps again.
I think it should first try to refresh the cache, but if it is not successful leave the existing files alone.
Thanks.

**Comment by activityworkshop** [comment]
You're right, it should leave the existing files alone.  If you select offline mode (uncheck Settings -> Load maps from internet) then it doesn't try to download any tiles and just uses the ones in the cache, no matter how old they are.

It seems like in your case it sees that the tile is old, sees that you've selected to download new tiles from the internet, tries to do this, and fails.  It's here that the existing tile gets deleted.

It should be an easy fix, but it has just missed the window for 18.4.

**Comment by jbergenthal2** [comment]
Ah, great. (uncheck Settings -> Load maps from internet). That's what I needed, thanks for pointing that up. Cheers.

**Comment by activityworkshop** [comment]
I'll close this issue because I believe it is now fixed with version 18.5.
