### ISSUE TITLE
Feature Request: Remember track compression parameters between sessions

### ISSUE THREAD

**Issue by lenlo** [activityworkshop/GpsPrune#51]
It would be great if GpsPrune could remember the compression parameters between sessions so I didn't have to reenter them every time I run GpsPrune.

Background: I record my runs using Strava and afterwards bring them up into GpsPrune to straighten them out, but every time I do this I first need to compress the tracks as they contain too many points. I always use the same compression parameters, but because they are different from GpsPrune's default, I have to reenter them every time I start the program anew. They are currently remembered only for the duration of the run session, but it would be great if they could be remembered between sessions too (or, barring this, if the default values could be set in a configuration file).

Thanks!

**Comment by activityworkshop** [comment]
done :)
