### ISSUE TITLE
Track size reduction factor no longer affects .pov

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#55]
The problem is that gpsprune always built 3d with a track too large in diameter, for example it is mentioned here https://github.com/activityworkshop/GpsPrune/issues/49#issue-1205544358

Previously, you could change the block in the .pov file:
```
#declare track_sphere0 =
   sphere {
    <0, 0, 0>, 0.3
```

by the coefficient `<0, 0, 0>, 0.135.` And the track was shrinking nicely. But in the latest version of gpsprune, any values ​​of the coefficient do not affect the diameter of the track size, it is still very large.
How to reduce it?

**Comment by activityworkshop** [comment]
Issue 49 has been addressed and its solution will be released with version 22.  If you would like to contribute a translation for this new field (Finnish or Russian or any other language), then please do!  You can use the Sourceforge wiki or the Translatinator ( https://activityworkshop.net/translate/project?id=gpsprune ) or even just post the text here if you prefer.

It has always been possible to edit the pov by hand, and this is still possible, nothing has changed.  So if it used to work before, then it works now.
