### ISSUE TITLE
Settings for getting SRTM heights with higher accuracy do not work

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#56]
![0](https://user-images.githubusercontent.com/61022210/175761683-4ed7d0b8-3796-415b-8f3d-01cc3e0dc88e.png)
Random login password accepted.

When receiving online heights (1 second, NASA account), the login / password form accepts any random data and saves (does not display that there is no error). A check mark is placed that the user is logged into his account and when trying to load the heights, they are loaded explicitly without using the account (nasa / 1 second), but misleading the user.

In addition, I have a real NASA account, when I enter its data, I still get online heights from 20 years ago (3 seconds instead of 1 second).

**Comment by snooppr** [comment]
There is a track with a distance of **270 km.**
Here is its height calculated in gpsrune (3 arcseconds)
1. ![SRTM 90](https://user-images.githubusercontent.com/61022210/175805950-238aaa3b-ad8c-44dc-96af-9e970df4d67c.png)
climb is: **3370m**.

------------------------------------

2. Processed the same track in qgis SRTM (1 arc second) and simply loaded into gps prune)
![SRTM 30](https://user-images.githubusercontent.com/61022210/175806019-6d8349ae-b5e1-45c0-9fb9-a7b0bb8f8499.png)
climb is: **4355m**.

------------------------------------

3. same track on google earth
![google earth](https://user-images.githubusercontent.com/61022210/175806056-bcea3480-3e1b-4d84-9c82-d5789a9d266b.png)
climb is: **1278m**.

------------------------------------

4. same track in osmand
![osmand](https://user-images.githubusercontent.com/61022210/175806480-58a209f0-df71-49e6-b78e-59d813a11f53.jpeg)
climb is: **2879m**.

------------------------------------

5. same track at https://activetrip.me/
![activetrip_me](https://user-images.githubusercontent.com/61022210/175806144-5ab5adbc-6d49-4f7d-81f3-399eedff810a.png)
climb is: **1063m**.

------------------------------------

6. the same track in https://nakarte.me
![nakarte_me](https://user-images.githubusercontent.com/61022210/175806167-8996e679-bf20-4b2e-aa05-d84cbf5469d5.png)
climb is: **1324m**.

------------------------------------

7. the same track at https://gpx.studio/
![gpx studio](https://user-images.githubusercontent.com/61022210/175806208-fde69072-a4bc-45cb-9ad7-60fee1d63d03.png)
climb is: **1643m**.

Worryingly for the calculation of the height in gpsprune, the overestimation is significant (can you double-check the algorithms for calculating the height?).


------------------------------------


experimental [track.gpx](https://disk.yandex.ru/d/Are-QgdAVRfwOg)

**Comment by activityworkshop** [comment]
When you enter your username and password, it saves this information in the settings, but it doesn't send anything to Nasa.  It doesn't login, so it doesn't check whether the password is valid or not.  The username and password are used when you request SRTM tiles.

If you already have the required tiles in your cache, then it won't need to contact the server so it doesn't matter whether the password is correct or not, you already have the data you need.

If 1-second data isn't available, or if your password is incorrect, it will fall back to 3-second data, and again will use data from your cache if it can.
