### ISSUE TITLE
How to view the trackpoint list for a dragged *.gpx file?

### ISSUE THREAD

**Issue by pstein** [activityworkshop/GpsPrune#60]
I have dragged a *.gpx file into GPSprune.
The route is visible on the corresponding map and even the altitude diagram is visible.

But how exactly can I let GPS prune show the full trackpoint list?

**Comment by activityworkshop** [comment]
GpsPrune never shows a "full trackpoint list", if by that you mean a grid showing every single point in the track and all its fields.

Instead, it shows a list of waypoint names, on the left (if there are any) and it shows the details of the currently selected point on the right.  If you want to see the details of any point in the track, just select it (click on the map or click on the altitude diagram) and you'll see its details on the right.  If those details aren't enough for you then go to the menu "View -> Full details".

**Comment by pstein** [comment]
> GpsPrune never shows a "full trackpoint list", if by that you mean a grid showing every single point in the track and all its fields.
> 

This is VERY bad.
This feature should be added in future versions

**Comment by activityworkshop** [comment]
why?

**Comment by activityworkshop** [comment]
It's been more than a year, so I guess we're not going to get an answer to this one :/
