### ISSUE TITLE
cannot enter shape-scale-factor smaller than 1 for 3D-View

### ISSUE THREAD

**Issue by jannis701** [activityworkshop/GpsPrune#63]
I want to use the new option of 3D-view (see #49) to make the dots of the track _smaller_. Therefore I'd like to enter a value between 0 and 1 for shape-scale-factor. 

But  the field for shape-scale-factor allows only digits and "," and if I enter a value with "," e.g. "0,4" it looks as if I enter "0"

I'd like to try to enter "0.4" (with dot "."), but it is not possible  (maybe, because my system is locale DE-de ?)

**Comment by snooppr** [comment]
analog https://github.com/activityworkshop/GpsPrune/issues/62

**Comment by activityworkshop** [comment]
as noted, this is exactly the same as 62.
