### ISSUE TITLE
macOS region/locale/preferred language setting affecting timestamps in GPX export

### ISSUE THREAD

**Issue by sanketgarade** [activityworkshop/GpsPrune#79]
In the below screenshot you can see that my macos is set to region = India and preferred language = Marathi, but numbering system is set to 123 instead of १२३.

On the right side are 3 gpx files -

- top - original gpx file (recorded in osmAnd)
- middle - gpx file exported from gpsprune without any modifications
- bottom - gpx file exported from gpsprune after applying a time offset

In the bottom one, the issue is that the timestamps `<time>` change from english numbers (123) to Devanagari numbers (१२३) and hence the GPX file become unreadable by other software.

Could you please fix this such that all timestamps continue to be in English (123 system)?

![Screenshot 2023-06-28 at 8 24 08 AM](https://github.com/activityworkshop/GpsPrune/assets/74632379/12dc0084-bfee-49c5-a5eb-af16b48c3ceb)

**Comment by activityworkshop** [comment]
Thanks for the bug report.
It looks like the java timestamp formatting is actually doing _too good_ a job of localizing the formatting according to your system settings.  I haven't seen this issue before so thanks for pointing it out.

I guess that the fix will just be to specify a Locale to use for the formatting (and I guess that using a "US" Locale would be sufficient) instead of just letting it use the default system Locale.  This seems pretty minor so it can come easily with version 23.1.  It would be great if you could test this for me when it's ready.

**Comment by sanketgarade** [comment]
Thanks. Yes sure, I can help test it.

**Comment by activityworkshop** [comment]
I'm curious what happens with altitudes, is the same problem there too?
If a GPX file has a point with an altitude of 123 metres, and you edit this altitude (either with the "edit point" function or with the "add altitude offset" function), does the new altitude get written with 123 numbers or Devanagari numbers?

**Comment by sanketgarade** [comment]
changed only the altitude via the Edit point tool and (in the exported gpx file) the altitude remains in 123 format while the time changes to Devanagari format.

Snaps and exported gpx text for reference -

before
![image](https://github.com/activityworkshop/GpsPrune/assets/74632379/03734ba5-c8a9-4a6d-929f-b1e9c0593506)

after
![image](https://github.com/activityworkshop/GpsPrune/assets/74632379/397dc1b8-b2a3-4a3c-b93b-747b6db95760)

```
<trkpt lat="18.601697999999995" lon="73.70981799999997"><ele>699.811</ele><time>2023-06-17T00:49:35Z</time></trkpt>
<trkpt lat="18.601715999999996" lon="73.70976799999997"><ele>710</ele><time>२०२३-०६-१७T००:४९:४२Z</time></trkpt>
<trkpt lat="18.601741999999994" lon="73.70971699999997"><ele>700.727</ele><time>2023-06-17T00:49:48Z</time></trkpt>
```

**Comment by activityworkshop** [comment]
Could you please try with this jar?
https://gpsprune.activityworkshop.net/gpsprune_23.1_test.jar
Thanks!

**Comment by sanketgarade** [comment]
works as expected! thanks for the fix 😃

**Comment by activityworkshop** [comment]
Yes, exactly.
Thanks for testing, I'll get this all wrapped up into a new 23.1.
