### ISSUE TITLE
Could not open *.gdx

### ISSUE THREAD

**Issue by theScrabi** [activityworkshop/GpsPrune#8]
Hello,

I've tried to open .gdx files with, but it always prints "File could not be read: <filename>.gdx", I would like to find out why it failed, but I could not find any log output.
How can this be fixed?

rgds Schabi

**Comment by activityworkshop** [comment]
Sorry for the delay in replying.
I've never used gdx files so I'll have to ask some questions first:  Are you using GPSBabel to open the file (File -> Import file using GPSBabel)?  Is your version of GPSBabel up-to-date?  What is the file and where did it come from?  Have you got any other programs which can open these files?

One thing I would suggest is trying to open a file using GPSBabel from the command line, and seeing if it gives any more detailed error message.  Have you tried that?  Are you sure that the files you're trying to load are complete / not corrupted?

**Comment by theScrabi** [comment]
No I use a script to import the files.
So do I have to convert them again? What file format is GpsPrune using?

**Comment by activityworkshop** [comment]
GpsPrune can read gpx files, kml/kmz files, text/csv files and nmea files.  For most cases, gpx is most convenient. See https://activityworkshop.net/software/gpsprune/how-tos.html for basic instructions on loading files.

In addition, GpsPrune can use GPSBabel to do the conversion, so GpsPrune can in this way load any file supported by GPSBabel (which is dozens, see https://www.gpsbabel.org/capabilities.html ).  GpsPrune can also use GPSBabel to load data directly out of GPS receivers.

If you want GpsPrune to load data from your script, then your script should output one of the formats which GpsPrune understands, like for example gpx if you can write xml, or most simply any kind of comma-separated, semicolon-separated or tab-separated text file.  GpsPrune can't read binary formats itself (except kmz or gpx.zip), so you'll need to import these through GPSBabel.

If you have a user guide, all the options are covered in chapter 4, "Loading data".

**Comment by theScrabi** [comment]
I was this far trust me xD
I had xml bast .gpx files. And gpsprune tould me it could not load them.

So and so it would be nice if your app could give a more detailed info on why it could not load the file. So I could tell you more about the issue.

**Comment by activityworkshop** [comment]
It sounds to me like you tried to load a file called ".gdx".  Does that file exist, and is it a gpx file or a gdx file?
Are you giving the filename as a command line parameter to GpsPrune?  Are there spaces in your filename?

**Comment by theScrabi** [comment]
Aw g*d damed. You where right. The files where gpx files, but they had the ending gdx, so gpsprune did not know how to open them. I renamed them, and now gpsprune can load them.

Thanks :)
