### ISSUE TITLE
OpenStreetMap map backgrounds use deprecated {a,b,c}.tile.openstreetmap.org

### ISSUE THREAD

**Issue by jtn20** [activityworkshop/GpsPrune#86]
OpenStreetMap have deprecated the hostnames `{a,b,c}.tile.openstreetmap.org` in favour of just `tile.openstreetmap.org` -- see openstreetmap/operations#737.

I can see these deprecated tile server names still referenced in the current code:

https://github.com/activityworkshop/GpsPrune/blob/06d9ff3e10971bd586137862d93103adb1a2a0f7/src/tim/prune/gui/map/MapSourceLibrary.java#L41-L43

(It's actually Debian's gpsprune 20.2-1 where I've been observing complaints about this on the console, but since the old names are still on the head of `master` at time of writing, I assume it's still an issue with the current version.)

**Comment by activityworkshop** [comment]
Hi, and thanks for the information.

You're right, that's still an issue with the current version, as I was unaware of the change.
As far as I can tell, the "old" URLs still work, like for example this one https://a.tile.openstreetmap.org/6/37/26.png and by scrolling around I can see that GpsPrune is still able to retrieve tiles currently.  But of course I'll update the URLs for the next release, which will be either 23.2 or 24.
