### ISSUE TITLE
Layer 'aerial' photo orthoplanes for 3D Missing in gpsprune

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#97]
I found a [video](https://www.youtube.com/watch?v=ZJmfKeRqZDE) on YouTube from gpsprune about preparing a track in 3D, there was an 'aerial' (4m:32s) layer in the drop-down menu, but on GNU/Linux gpsprune v23 is missing.
Was it removed from the software, or was it something experimental?

Here is the layer itself:
![aerial](https://github.com/activityworkshop/GpsPrune/assets/61022210/06839ae2-5eb6-43e8-9594-d4a93c9fd875)

**Comment by activityworkshop** [comment]
It's not "missing", it's just not one of the ones included by default.
That one was added separately, using Settings -> Set map background -> Add new.
You can add any number of sources you like yourself.

**Comment by snooppr** [comment]
>You can add any number of sources you like yourself.

As far as I understand, space images under a free license or for personal use are not so easy to obtain. For example, I believe that Google Images will never indicate tiles. In any case, I did not find a single third-party URL for tiles in the instructions. But I understand the meaning, thank you, I'll close this.

**Comment by activityworkshop** [comment]
You're right, usually the use of aerial imagery is covered by Terms and Conditions.  Using Google's images is technically possible with GpsPrune but forbidden by Google.  Bing is similar I think.

The source used in that video is allowed for personal use, but it only covers a limited area, so it makes no sense to add it as a global default source. But if you find a source for your area then as mentioned earlier you can just add it for yourself and store it in your settings.
