### ISSUE TITLE
3D mode is broken in new versions of openjdk. Update the instructions on the website.

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#98]
Suddenly the 3D mode in gpsprune stopped working on my GNU/Linux. I tried reinstalling the software of different versions of gpsprune, but no luck. I went to study the instructions on the gpsprune website to understand what was happening. The instructions say that gpsprune works with java8+. I looked at my version:
`$ java --version`
> openjdk 17.0.6 2023-01-17

`$ javac --version`
> javac 11.0.13

I ran gpsprune in the terminal to get some logs and got (when trying to use 3D mode):
>Exception in thread "J3D-Renderer-1" java.lang.IllegalAccessError: class javax.media.j3d.X11NativeConfigTemplate3D (in unnamed module @0x59320757) cannot access class sun.awt.X11GraphicsConfig (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x59320757
	at javax.media.j3d.X11NativeConfigTemplate3D.getBestConfiguration(X11NativeConfigTemplate3D.java:75)
	at javax.media.j3d.NativePipeline.getBestConfiguration(NativePipeline.java:3335)
	at javax.media.j3d.Renderer.doWork(Renderer.java:514)
	at javax.media.j3d.J3dThread.run(J3dThread.java:275)

An error [search on Google](https://www.google.com/search?q=Exception+in+thread+%22J3D-Renderer-1%22+java.lang.IllegalAccessError%3A+class+javax.media.j3d.X11NativeConfigTemplate3D&sca_esv=00b1959cab87582d&ei=PvLBZYW_Gd38wbkPnK6W-A0&udm=&ved=0ahUKEwiF1uOUqpaEAxVdfjABHRyXBd8Q4dUDCBA&uact=5&oq=Exception+in+thread+%22J3D-Renderer-1%22+java.lang.IllegalAccessError%3A+class+javax.media.j3d.X11NativeConfigTemplate3D&gs_lp=Egxnd3Mtd2l6LXNlcnAickV4Y2VwdGlvbiBpbiB0aHJlYWQgIkozRC1SZW5kZXJlci0xIiBqYXZhLmxhbmcuSWxsZWdhbEFjY2Vzc0Vycm9yOiBjbGFzcyBqYXZheC5tZWRpYS5qM2QuWDExTmF0aXZlQ29uZmlnVGVtcGxhdGUzREgAUABYAHAAeACQAQCYAQCgAQCqAQC4AQPIAQDiAwQYACBB&sclient=gws-wiz-serp) reported that openjdk does not seem to work with 3D from version 16 and above.

Actually the solution that helped me (3D mode worked again):
`$ sudo update-alternatives --config java`
>
  0            /usr/lib/jvm/java-17-openjdk-amd64/bin/java      1711      автоматический режим
  1            /usr/lib/jvm/java-10-openjdk-amd64/bin/java      1101      ручной режим
  **2            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      ручной режим**
  3            /usr/lib/jvm/java-17-openjdk-amd64/bin/java      1711      ручной режим
  4            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      ручной режим
  5            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      ручной режим

If I had immediately found information in the instructions on the site that the 3D mode does not work with OpenJDK v16+. It would save me time.

**Please update the gpsprune instructions for users on your website.**

**Comment by activityworkshop** [comment]
The version of `javac` is irrelevant, it's important which version of the Java runtime you're using which in your case was 17 and now you've switched it to 11.  But yes, in general the information that GpsPrune works with java 8+ is accurate.

The problem you saw with java 17 is to do with module access, and is described on the website at the bottom of this page: https://activityworkshop.net/software/gpsprune/problem-solving.html
