### ISSUE TITLE
activityworkshop.net domain registration expired

### ISSUE THREAD

**Issue by sebastic** [activityworkshop/GpsPrune#99]
The Debian package is unable to check for new releases:
```
$ uscan --report
uscan warn: In watchfile debian/watch, reading webpage
  https://activityworkshop.net/software/gpsprune/download.html failed: 500 Can't connect to activityworkshop.net:443 (Connection refused)
```

The site now shows:
> The requested domain is currently not reachable, because the registration period of the domain has expired. The domain has not been renewed or automatic deletion has been initiated.
> 
> If you are the domain owner and want to renew the domain, please contact your registration service provider.

**Comment by activityworkshop** [comment]
Thanks for the information. Yes you're right this happened unexpectedly yesterday. I'm trying to get it fixed.

**Comment by activityworkshop** [comment]
Seems to be fixed now. Sorry for the disturbance!
